### ISSUE TITLE
Add Automatic Build Artifact Creation and Uploading

### ISSUE THREAD

**Issue by indiv0** [indiv0/colonize#11]
The capability to generate build artifacts (e.g. `.exe`s) needs to be added to Travis CI and Appveyor.

These artifacts should automatically be added to releases.
# Status
- [ ] `unknown-linux`
  - [ ] `unknown-linux-gnu`
    - [ ] `i686-unknown-linux-gnu` (functionality added in #58, needs testing)
      - works, but needs to be packaged with `assets/` directory
    - [ ] `x86_64-unknown-linux-gnu` (functionality added in #58, needs testing)
      - works, but needs to be packaged with `assets/` directory per
  - [ ] `unknown-linux-musl`
    - [ ] `x86_64-unknown-linux-musl` (blocked by #60, tracked at #65)
- [ ] `apple-darwin`
  - [ ] `i686-apple-darwin` (functionality added in #58, currently broken per #67)
  - [ ] `x86_64-apple-darwin` (blocked by #59, tracked at #66)
- [ ] `pc-windows`
  - [ ] `pc-windows-gnu`
    - [ ] `i686-pc-windows-gnu`
    - [ ] `x86_64-pc-windows-gnu`
  - [ ] `pc-windows-msvc`
    - [ ] `i686-pc-windows-msvc`
    - [ ] `x86_64-pc-windows-msvc`

**Comment by indiv0** [comment]
For Windows builds, ensure that the release builds are built with the following command (this is necessary to that it doesn't display the console window when the game is run):

```
cargo rustc --no-default-features --features nightly --release -- -C link_args="-Wl,--subsystem,windows"
```

**Comment by indiv0** [comment]
For further optimization, add `-s` to the `link_args` above and add `-C opt-level=3`.
Initial testing shows the performance gains from this to be negligible (<5 FPS) but it shrinks the binary size by 40%.

**Comment by indiv0** [comment]
And once https://github.com/tomaka/glutin/issues/756 is fixed, we should utilize LTO for further optimization.

**Comment by indiv0** [comment]
Additionally, we should check if LTO works with non-glutin backends.
