### ISSUE TITLE
Update `README.md`

### ISSUE THREAD

**Issue by indiv0** [indiv0/colonize#13]
# Status

* [x] Update building instructions (#58)
* [x] Add information on pre-compiled binaries (#58)
* [x] Update the badges (#58)
    * [x] API Docs (#58)
    * [x] Travis CI (#58)
    * [x] ~~crates.io (#58)~~
    * [x] coveralls.io (#58)
* [x] Add a screenshot (#61)
* [x] Add a notice regarding the `CHANGELOG.md`
* [ ] Add information regarding supported platforms and toolchains (#75)
    * This will help avoid issues like #49.
* [x] Add a "Contributing" section (requires #72)
* [x] Add a "Credits" section (requires #73)
* [x] Add a "License" section (ties into #74)
* [ ] Remove crates.io badge
